### ISSUE TITLE
Change harvester approach to update instead of delete and reinsert

### ISSUE THREAD

**Issue by tigreped** [WingLongitude/lontra-harvester#9]
The lontra harvester currently deletes occurrence data and inserts upon re-indexing. Support update operations instead, to allow auto_id maintenance.

**Comment by tigreped** [comment]
Issue solved, as SiBBr will revert its behavior to be the same as Canadensys.

**Comment by cgendreau** [comment]
We won't update records for now but we will keep the id between harvest when possible.
See Issue #14
